.PHONY: status discover check handshake auth render validate bundle

status:
	./bin/niurk-flow.sh status

discover:
	./bin/niurk-flow.sh discover

check:
	./bin/niurk-flow.sh check

handshake:
	./bin/niurk-flow.sh handshake

auth:
	./bin/niurk-flow.sh auth

render:
	./bin/niurk-flow.sh render

validate:
	./bin/niurk-flow.sh validate

bundle:
	cd .. && zip -r niurk-smart-workflow-bundle.zip niurk-smart-workflow-bundle
