
(()=>{
  const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
  const canvas=$('#glyphCanvas'), ctx=canvas.getContext('2d');
  const state={glyph:null, time:0, animate:false, params:{strokeWidth:4,curvature:72,tension:58,rhythm:65,branching:22,axis:34,momentum:61,morph:38}, display:{grid:true,outlines:true,points:true,handles:true,symmetry:true}, drag:null, tfStatus:'booting'};
  const familyChars={root:'A',bridge:'∞',form:'V',rhythm:'〰',nature:'ψ',momentum:'λ',axiom:'☉'};
  function resize(){const r=canvas.parentElement.getBoundingClientRect(); canvas.width=Math.floor(r.width*devicePixelRatio); canvas.height=Math.floor(r.height*devicePixelRatio); canvas.style.width=r.width+'px'; canvas.style.height=r.height+'px'; ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0); draw();}
  function init(){ state.glyph=FlowformsGlyphs.glyphs.find(g=>g.char==='F')||FlowformsGlyphs.glyphs[0]; buildFamilies(); buildGlyphGrid(); buildPlanches(); bind(); resize(); requestAnimationFrame(loop); FlowTensorAgent.train().then(r=>{state.tfStatus=r.ok?'tfjs trained':'rule engine'; updateStatus();}); }
  function buildFamilies(){const el=$('#families'); el.innerHTML=''; for(const [key,f] of Object.entries(FlowformsGlyphs.families)){const div=document.createElement('div'); div.className='family '+(key===state.glyph.family?'active':''); div.innerHTML=`<div class="glyphicon">${familyChars[key]||'☉'}</div><div><h3>${f.label}</h3><p>${f.axiom}</p></div><div>⌄</div>`; div.onclick=()=>{const g=FlowformsGlyphs.glyphs.find(x=>x.family===key && x.char.length===1)||state.glyph; selectGlyph(g.char)}; el.appendChild(div);} }
  function buildGlyphGrid(filter=''){const grid=$('#glyphGrid'); grid.innerHTML=''; const glyphs=FlowformsGlyphs.glyphs.filter(g=>g.char.length===1 && (/[A-Za-z0-9]/.test(g.char))).filter(g=>!filter||g.char.toLowerCase().includes(filter.toLowerCase())||g.name.includes(filter.toLowerCase())||g.family.includes(filter.toLowerCase())).slice(0,72); for(const g of glyphs){const d=document.createElement('button'); d.className='glyph-tile '+(state.glyph.char===g.char?'active':''); d.innerHTML=`<div class="g">${g.char}</div><div class="c">${g.char}</div>`; d.onclick=()=>selectGlyph(g.char); grid.appendChild(d);} }
  function buildPlanches(){const left=$('#planches'); left.innerHTML=''; const groups=['root','bridge','form','rhythm','nature','momentum','axiom']; groups.forEach(k=>{const gl=FlowformsGlyphs.glyphs.filter(g=>g.family===k).slice(0,6).map(g=>g.char).join(''); const m=document.createElement('div'); m.className='mini'; m.innerHTML=`<div class="glyphs">${gl}</div><span>${FlowformsGlyphs.families[k].label}</span>`; left.appendChild(m);}); const sy=$('#symbolsets'); sy.innerHTML=''; [['Numerals','01234<br>56789'],['Punctuation','.,:;!?<br>—_()'],['Solar','☉✦OQ'],['Decorative','〰∞φψ']].forEach(([a,b])=>{const m=document.createElement('div');m.className='mini';m.innerHTML=`<div class="glyphs">${b}</div><span>${a}</span>`;sy.appendChild(m);}); }
  function bind(){window.addEventListener('resize',resize); $('#glyphSearch').oninput=e=>buildGlyphGrid(e.target.value); $$('input[type=range][data-param]').forEach(sl=>{sl.oninput=()=>{state.params[sl.dataset.param]=+sl.value; sl.parentElement.querySelector('span').textContent=sl.dataset.param==='strokeWidth'?sl.value+' px':sl.value+'%'; draw(); updateStatus();};}); $$('[data-toggle]').forEach(t=>t.onclick=()=>{const k=t.dataset.toggle; state.display[k]=!state.display[k]; t.classList.toggle('on',state.display[k]); draw();}); $('#animateBtn').onclick=()=>{state.animate=!state.animate; $('#animateBtn').textContent=state.animate?'Pause Path':'Animate Path'}; $('#variantBtn').onclick=generateVariants; $('#exportSvgBtn').onclick=exportSvg; $('#exportFontBtn').onclick=()=>showModal('Font asset', 'The generated font files are inside web/fonts/Flowforms-Regular.ttf and Flowforms-Regular.svg. Use the bundle Makefile or Docker image to serve them.'); $('#saveGlyphBtn').onclick=saveGlyph; $('#formalBtn').onclick=()=>showFormal(); canvas.addEventListener('pointerdown',down); canvas.addEventListener('pointermove',move); window.addEventListener('pointerup',()=>state.drag=null); }
  function selectGlyph(ch){const g=FlowformsGlyphs.glyphs.find(x=>x.char===ch); if(g){state.glyph=g; buildGlyphGrid($('#glyphSearch').value); buildFamilies(); draw(); updateStatus();}}
  function transform(){const r=canvas.getBoundingClientRect(); const scale=Math.min(r.width/720,r.height/820); const ox=r.width/2-280*scale, oy=r.height/2-350*scale; return {scale,ox,oy};}
  function screenToDesign(x,y){const t=transform(); return [(x-t.ox)/t.scale,(y-t.oy)/t.scale];}
  function renderGlyph(g, style={}){ctx.save(); const t=transform(); ctx.translate(t.ox,t.oy); ctx.scale(t.scale,t.scale); ctx.lineCap='round'; ctx.lineJoin='round'; ctx.strokeStyle=style.stroke||'#111'; ctx.globalAlpha=style.alpha==null?1:style.alpha; ctx.lineWidth=style.width||state.params.strokeWidth*2.2; for(const s of g.strokes){ctx.beginPath(); ctx.moveTo(...s.p0); ctx.bezierCurveTo(...s.c1,...s.c2,...s.p1); ctx.stroke();} ctx.fillStyle=style.stroke||'#111'; for(const d of g.dots||[]){ctx.beginPath(); ctx.arc(d.x,d.y,d.r,0,Math.PI*2); ctx.fill();} ctx.restore();}
  function renderHandles(g){const t=transform(); ctx.save(); ctx.translate(t.ox,t.oy); ctx.scale(t.scale,t.scale); ctx.lineWidth=1/t.scale; for(const s of g.strokes){ctx.strokeStyle='rgba(112,96,72,.5)'; ctx.fillStyle='#fffdf8'; [['p0','c1'],['p1','c2']].forEach(([a,b])=>{ctx.beginPath();ctx.moveTo(...s[a]);ctx.lineTo(...s[b]);ctx.stroke();}); ['p0','p1'].forEach(k=>{ctx.beginPath();ctx.arc(s[k][0],s[k][1],5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#111';ctx.stroke();}); ['c1','c2'].forEach(k=>{ctx.beginPath();ctx.rect(s[k][0]-4,s[k][1]-4,8,8);ctx.fill();ctx.strokeStyle='#a98152';ctx.stroke();});} ctx.restore();}
  function draw(){if(!ctx||!state.glyph)return; const r=canvas.getBoundingClientRect(); ctx.clearRect(0,0,r.width,r.height); const base=state.glyph; const mod=FlowMath.modulate(base,state.params,state.time); if(state.display.outlines){renderGlyph(FlowMath.variant(base,.22,state.params),{stroke:'#9d9588',alpha:.25,width:2}); renderGlyph(FlowMath.variant(base,1.7,state.params),{stroke:'#9d9588',alpha:.18,width:2});} renderGlyph(mod,{stroke:'#111',alpha:1,width:state.params.strokeWidth*2.4}); if(state.display.handles||state.display.points) renderHandles(mod); updateVariants(mod);}
  function updateVariants(g){const box=$('#variants'); box.innerHTML='<h4>VARIANTS</h4>'; for(let i=0;i<4;i++){const card=document.createElement('div'); card.className='variant-card '+(i===1?'active':''); card.textContent=g.char; card.style.fontVariationSettings='normal'; card.onclick=()=>{state.params.morph=(i+1)*18; $('[data-param="morph"]').value=state.params.morph; draw();}; box.appendChild(card);} }
  function loop(ts){state.time=ts/1000; if(state.animate) draw(); requestAnimationFrame(loop);}
  function nearest(pt){let best=null,dist=18; const g=state.glyph; for(let si=0;si<g.strokes.length;si++){const s=g.strokes[si]; for(const k of ['p0','c1','c2','p1']){const d=Math.hypot(s[k][0]-pt[0],s[k][1]-pt[1]); if(d<dist){dist=d;best={si,k};}}} return best;}
  function down(e){const pt=screenToDesign(e.offsetX,e.offsetY); state.drag=nearest(pt);}
  function move(e){if(!state.drag)return; const pt=screenToDesign(e.offsetX,e.offsetY); state.glyph.strokes[state.drag.si][state.drag.k]=pt; draw(); updateStatus();}
  async function updateStatus(){const g=state.glyph; const f=FlowMath.features(g); const assert=FlowTensorAgent.assertGlyph(g); const cls=await FlowTensorAgent.classify(g); $('#status').innerHTML=`<span>Active Glyph: <b>${g.char}</b></span><span>Unicode: U+${g.unicode.toString(16).padStart(4,'0').toUpperCase()}</span><span>Family: <b>${g.family}</b></span><span>Length: ${Math.round(f.length)}</span><span>Contours: ${g.strokes.length}</span><span>${assert.ok?'Coherent':'Needs smoothing'}</span><span class="spacer formula">L = ${FlowMath.lagrangian(FlowMath.modulate(g,state.params,state.time),state.params,state.time).toFixed(3)} · classifier: ${cls.family}/${cls.mode}</span>`;}
  function exportSvg(){const g=FlowMath.modulate(state.glyph,state.params,state.time); const path=FlowMath.toSvgPath(g); const circles=(g.dots||[]).map(d=>`<circle cx="${d.x}" cy="${d.y}" r="${d.r}"/>`).join(''); const src=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 560 700"><path d="${path}" fill="none" stroke="#111" stroke-width="${state.params.strokeWidth*2}" stroke-linecap="round" stroke-linejoin="round"/>${circles}</svg>`; download(`flowforms-${state.glyph.char}.svg`,src,'image/svg+xml'); }
  function saveGlyph(){const data=JSON.stringify(state.glyph,null,2); download(`flowforms-${state.glyph.char}.json`,data,'application/json');}
  function download(name,content,type){const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([content],{type})); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function generateVariants(){state.params.morph=(state.params.morph+17)%100; $('[data-param="morph"]').value=state.params.morph; draw(); updateStatus();}
  function showModal(title, body){$('#modalTitle').textContent=title; $('#modalBody').textContent=body; $('#modal').classList.add('show');}
  function showFormal(){showModal('Flowforms formal expression engine', `Real glyph function:\nFθ(s; r,p,a) = Aθ(Σ Bᵢ(s)Pᵢ + Φroot(s,r)+Φrhythm(s)+Φaxiom(s,a))\n\nLagrangian over control graph q = (P₀..Pₙ):\nL(q,q̇,t)= 1/2 q̇ᵀM q̇ - Vroot(q,r) - Vsmooth(q) - Vphoneme(q,p) + A(q,t)·q̇\n\nEuler-Lagrange / ODE:\nM q̈ + C q̇ + ∇V(q,t) - B(q,t)q̇ = u(t)\n\nThis canvas uses the reduced real-time ODE q̈ = -ηq̇ - ∇V + swirl(momentum) + rhythm forcing.`)}
  $('#modalClose').onclick=()=>$('#modal').classList.remove('show');
  window.addEventListener('DOMContentLoaded',init);
})();
